# Generated by Django 4.2.2 on 2023-06-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBoard',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('image', models.ImageField(upload_to='images', verbose_name='이미지 경로')),
                ('name', models.CharField(max_length=100, verbose_name='파일 이름')),
            ],
        ),
    ]
